#---
#title: "Election 2020 Analysis, Polarization"
#description: |
# Exploratory analysis of the increasing polarization across USA elections. 
#author:
 # - name: Keith Wescott
 #   url: https://github.com/kwescott21
#date: July 15th, 2021
#---

```{r}
#Download data from this link:
#https://drive.google.com/drive/folders/1Fkkyi6w9h0ZDo1vcuOaAVi-I-l2QXOYg?usp=sharing
#Place files in project folder. Data is too large to upload to GitHub

#Import 2020 Survey Data
library(haven)
RawData <- read_dta("anes_timeseries_2020_stata_20210324.dta")

#Import Long-Term Data
library(haven)
RawData_LongTerm <- read_dta("anes_timeseries_cdf.dta")
```

```{r}
#Install packages, only run if first time using file

#install.packages("skimr")
#install.packages("dplyr") # manipulate dataframes
#install.packages("readr") # read/write dataframes
#install.packages("tidyr") # reshaping dataframes
#install.packages("stringr") # string manipulation
#install.packages("forcats") # factor manipulation
#install.packages("purrr") # iteration (instead of loops)
#install.packages("ggplot2") # making plots
#install.packages("ggpmisc")
#install.packages("gapminder")
#install.packages("gganimate")
#install.packages("gifski")
#install.packages("broom")
#install.packages("ggpval")
#install.packages("tweenr")

```
```{r}
#open librarys for analysis
library(tidyverse)
library(readr)
library(tidyr)
library(stringr)
library(forcats)
library(purrr)
library(fs)
library(skimr)
library(ggpubr)
library(broom)
library(ggpmisc)
library(ggplot2)
library(gtsummary)
library(gt)
library(dplyr)
library(gapminder)
library(gganimate)
library(gifski)
library(ggpval)
library(tweenr)
```

```{r}
#Selecting columns to keep for analysis and renaming them to make user friendly
library(dplyr)
RawData_SC <- RawData %>% 
  select(
    sex = V201600,
    sexual_orientation = V201601,
    violence_justification = V201602,
    money_in_stocks = V201606,
    total_income = V201607,
    total_household_income = V201617x,
    has_health_insurance = V201620,
    positive_covid = V201624,
    guns_owned = V201628,
    remarks_sexist = V201639,
    women_power_over_men = V201640,
    life_satisfaction = V201651,
    voter_registered = V202056,
    party_of_registration = V202064,
    did_vote = V202066,
    did_vote_president = V202072,
    who_for_president = V202073,
    time_before_decision = V202075,
    did_vote_house = V202080,
    who_for_house = V202081,
    did_vote_senate = V202087,
    who_for_senate = V202091,
    summary_voter_turnout = V202109x,
    summary_presidential_vote = V202110x,
    how_voted_2020 = V202117,
    how_usually_vote = V202118,
    difficulty_voting = V202119,
    ft_joe_biden = V202143,
    ft_donald_trump = V202144,
    ft_kamala_harris = V202156,
    ft_mike_pence = V202157,
    ft_fauci = V202158,
    ft_christian_fund = V202159,
    ft_feminists = V202160,
    ft_liberals = V202161,
    ft_labor_unions = V202162,
    ft_big_business = V202163,
    ft_conservatives = V202164,
    ft_supreme_court = V202165,
    ft_gay_men_lesbians = V202166,
    ft_congress = V202167,
    ft_muslims = V202168,
    ft_christians = V202169,
    ft_jews = V202170,
    ft_police = V202171,
    ft_trans_people = V202172,
    ft_scientists = V202173,
    ft_blm = V202174,
    ft_journalists = V202175,
    ft_socialists = V202179,
    ft_capitalists = V202180,
    ft_me_too = V202183,
    ft_rural_americans = V202184,
    incumbant_job_in_district = V202204,
    public_officials_dont_care = V202212,
    votes_counted_fairly = V202219,
    immigration_levels = V202232,
    favor_oppose_citizenship = V202242x,
    government_reduce_income_inequality = V202257,
    summ_gov_reduce_income_inequality = V202259x,
    society_equal_opp = V202260,
    summ_economic_mobility = V202320x,
    favor_oppose_tax_millionaires = V202325,
    favor_oppose_vaccine_schools = V202329,
    climate_change_importance = V202333,
    favor_oppose_12k_basic_income = V202374,
    min_wage_keep_lower_raise = V202377
    
  )
```

```{r}
#Overview of data with selected columns
library(tidyverse)
head(RawData_SC, 10)
tail(RawData_SC, 10)

library(skimr)
skim(RawData_SC)

#summarize(RawData_SC)
```

```{r}
#Creating new datasets for numeric and character variables
#Converting to all numeric and exploring the data
RawData_SC_Num <- mutate_all(RawData_SC, function(x) as.numeric(as.character(x)))
library(skimr)
skim(RawData_SC_Num)

#library(DataExplorer)
#DataExplorer::create_report(RawData_SC_Num)

DataCharacters <- RawData_SC_Num
DataCharacters$who_for_president <- as.character(DataCharacters$who_for_president)
```

```{r}
#Change sex variables for graph
RawData_SC$sex <- as.character(RawData_SC$sex)
RawData_SC$sex[RawData_SC$sex == "1"] <- "Male"
RawData_SC$sex[RawData_SC$sex == "2"] <- "Female"
RawData_SC$sex[RawData_SC$sex == "-9"] <- "Refused"
RawData_SC_SCatter <- RawData_SC[!RawData_SC$sex == "Refused",]

#Trump vs Journalists Regression
library(ggpmisc)
library(ggplot2)
my.formula <- y ~ x
ggplot(data = RawData_SC_SCatter) +
  aes(x = ft_donald_trump, y = ft_journalists, color = factor(sex)) +
  geom_point(size = 0.5, alpha = 0.25) +
  geom_smooth(method=lm, se=TRUE, show.legend=TRUE,formula = my.formula) +
   stat_poly_eq(formula = my.formula, 
                aes(label = paste(..eq.label.., ..rr.label.., sep = "~~~")), 
                parse = TRUE) + 
  coord_cartesian(ylim = c(-10,110)) +
  scale_colour_manual(values =  c("Female" = "darkorange3",  "Male" = "springgreen4")) +
  labs(
    title = "Feeling Thermometers (0-100 rating) of Terms 'Trump' vs. 'Journalists'",
    subtitle = "Factored via Sex",
    x = "Trump",
    y = "Journalists",
    caption = "Data via ANES",
  )
```
```{r}
#Saving previous graph
ggsave(filename = "TrumpvJournalist.png", plot = last_plot(), path = "Visualizations")
 
```

```{r}
#P Value Analysis of above regressions
Fit_Trump_Journalist_Sex <- lm(ft_donald_trump ~ ft_journalists + sex, data = RawData_SC_SCatter)%>% 
    tidy()
view(Fit_Trump_Journalist_Sex)

Fit_Biden_Journalist_Sex <- lm(ft_joe_biden~ ft_journalists + sex, data = RawData_SC_SCatter)%>% 
    tidy()
view(Fit_Biden_Journalist_Sex)
```


```{r}
#Regression of feeling thermometer of terms "Biden" and "Journalists"
library(ggpmisc)
library(ggplot2)
my.formula <- y ~ x
ggplot(data = RawData_SC_SCatter) +
  aes(x = ft_joe_biden, y = ft_journalists, color = factor(sex)) +
  geom_point(size = 0.5, alpha = 0.25) +
  geom_smooth(method=lm, se=TRUE, show.legend=TRUE,formula = my.formula) +
   stat_poly_eq(formula = my.formula, 
                aes(label = paste(..eq.label.., ..rr.label.., sep = "~~~")), 
                parse = TRUE) + 
  coord_cartesian(ylim = c(-10,110)) +
  scale_colour_manual(values =  c("Female" = "darkorange3",  "Male" = "springgreen4")) +
  labs(
    title = "Feeling Thermometers (0-100 rating) of Terms 'Biden' vs. 'Journalists'",
    subtitle = "Factored via Sex",
    x = "Biden",
    y = "Journalists",
    caption = "Data via ANES",
  )
```

```{r}
#Saving previous plot
ggsave(filename = "BidenvJournalist.png", plot = last_plot(), path = "Visualizations")
 
```

```{r}
#Rename column "who for president" from numbres to their names
RawData_SC$who_for_president <- as.character(RawData_SC$who_for_president)
RawData_SC$who_for_president[RawData_SC$who_for_president == "1"] <- "Biden"
RawData_SC$who_for_president[RawData_SC$who_for_president == "2"] <- "Trump"
```

```{r}
#rural americans plot
library(tidyverse)
library(ggplot2)
ra_plot <- ggplot(data = RawData_SC) +
  aes(x =who_for_president, y = round(ft_rural_americans, digits = 0), fill=who_for_president) +
  geom_bar(stat = "summary",fun= "mean", width=1, color="gray1", position = 'dodge') +
  geom_text(stat = "summary", fun = "mean",
            position = position_dodge(width = 1),
            aes(y = stage(ft_rural_americans, after_stat = y / 2),group = round(after_stat(y)),
                label = round(after_stat(y),digits =0),vjust=0)) +
  scale_x_discrete(limits=c("Biden", "Trump")) +
  scale_y_continuous(limits=c(0, 100)) +
  scale_fill_manual(values =  c("Biden" = "blue",  "Trump" = "red")) +
  #geom_text(aes(label=round(..y..,2)), fun.y=mean, geom="text", vjust=-0.25, size=3.5, position=position_dodge(width=1))+
  theme_minimal() +
  theme(legend.position="none") +
  labs(
    title = "Term 'Rural Americans' ",
    x = NULL,
    y = NULL
  )
```

```{r}
#feminist plot
fem_plot <- ggplot(data = RawData_SC) +
  aes(x =who_for_president, y = round(ft_fauci,digits = 0), fill=who_for_president) +
  geom_bar(stat = "summary", width=1, color="gray1", position = 'dodge') +
  geom_text(stat = "summary", fun = "mean",
            position = position_dodge(width = 1),
            aes(y = stage(ft_fauci, after_stat = y / 2),group = round(after_stat(y)),
                label = round(after_stat(y),digits =0),vjust=0)) +
  scale_x_discrete(limits=c("Biden", "Trump")) +
  scale_y_continuous(limits=c(0, 100)) +
  scale_fill_manual(values =  c("Biden" = "blue",  "Trump" = "red")) +
  #geom_text(aes(label=round(..y..,2)), fun.y=mean, geom="text", vjust=-0.25, size=3.5, position=position_dodge(width=1))+
  theme_minimal() +
  theme(legend.position="none") +
  labs(
    title = "Term 'Fauci'",
     x = NULL,
     y = NULL
  )
```

```{r}
#muslim plot
mus_plot <- ggplot(data = RawData_SC) +
  aes(x =who_for_president, y = round(ft_muslims, digits=0), fill=who_for_president) +
  geom_bar(stat = "summary", width=1, color="gray1", position = 'dodge') +
  geom_text(stat = "summary", fun = "mean",
            position = position_dodge(width = 1),
            aes(y = stage(ft_muslims, after_stat = y / 2),group = round(after_stat(y)),
                label = round(after_stat(y),digits =0),vjust=0)) +
  scale_x_discrete(limits=c("Biden", "Trump")) +
  scale_y_continuous(limits=c(0, 100)) +
  scale_fill_manual(values =  c("Biden" = "blue",  "Trump" = "red")) +
  #geom_text(aes(label=round(..y..,2)), fun.y=mean, geom="text", vjust=-0.25, size=3.5, position=position_dodge(width=1))+
  theme_minimal() +
  theme(legend.position="none") +
  labs(
    title = "Term 'Muslims' ",
     x = NULL,
     y = NULL
  )
```

```{r}
#me too plot
me_too_plot <- ggplot(data = RawData_SC) +
  aes(x =who_for_president, y = round(ft_me_too, digits=0), fill=who_for_president) +
  geom_bar(stat = "summary", width=1, color="gray1", position = 'dodge') +
  scale_x_discrete(limits=c("Biden", "Trump")) +
  geom_text(stat = "summary", fun = "mean",
            position = position_dodge(width = 1),
            aes(y = stage(ft_me_too, after_stat = y / 2),group = round(after_stat(y)),
                label = round(after_stat(y),digits =0),vjust=0)) +
  scale_y_continuous(limits=c(0, 100)) +
  scale_fill_manual(values =  c("Biden" = "blue",  "Trump" = "red")) +
  #geom_text(aes(label=round(..y..,2)), fun.y=mean, geom="text", vjust=-0.25, size=3.5, position=position_dodge(width=1))+
  theme_minimal() +
  theme(legend.position="none") +
  labs(
    title = "Term 'Me Too' ",
     x = NULL,
     y = NULL
  )
```

```{r}
#plot final combined graphs above
library(ggplot2)
figure1 <- ggarrange(ra_plot, fem_plot, mus_plot, me_too_plot, common.legend = TRUE, legend="bottom") 

 annotate_figure(figure1,
               top = text_grob("Feeling Thermometer Averages - Dissagreements by Presidential Vote", color = "firebrick4", face = "bold", size = 14),
               bottom = text_grob("Data source: ANES", color = "grey5",
                                  hjust = 1, x = 1, face = "italic", size = 10),
               left = text_grob("Feeling Thermometer Rated 0-100", color = "grey5", rot = 90))

```

```{r}
#Saving previous plot
ggsave(filename = "Feeling Thermometer Disagreements.png", plot = last_plot(), path = "Visualizations")
 
```

```{r}
#congress plot
con_plot <-ggplot(data = RawData_SC) +
  aes(x =who_for_president, y = ft_congress, fill=who_for_president) +
  geom_bar(stat = "summary", width=1, color="gray1", position = 'dodge') +
  geom_text(stat = "summary", fun = "mean",
            position = position_dodge(width = 1),
            aes(y = stage(ft_congress, after_stat = y / 2),group = round(after_stat(y)),
                label = round(after_stat(y),digits =0),vjust=0)) +
  scale_x_discrete(limits=c("Biden", "Trump")) +
  scale_y_continuous(limits=c(0, 100)) +
  scale_fill_manual(values =  c("Biden" = "blue",  "Trump" = "red")) +
  #geom_text(aes(label=round(..y..,2)), fun.y=mean, geom="text", vjust=-0.25, size=3.5, position=position_dodge(width=1))+
  theme_minimal() +
  theme(legend.position="none") +
  labs(
    title = "Term 'Congress' ",
     x = NULL,
     y = NULL
  )
```

```{r}
#big business plot
bus_plot <- ggplot(data = RawData_SC) +
  aes(x =who_for_president, y = ft_big_business, fill=who_for_president) +
  geom_bar(stat = "summary", width=1, color="gray1", position = 'dodge') +
  geom_text(stat = "summary", fun = "mean",
            position = position_dodge(width = 1),
            aes(y = stage(ft_big_business, after_stat = y / 2),group = round(after_stat(y)),
                label = round(after_stat(y),digits =0),vjust=0)) +
  scale_x_discrete(limits=c("Biden", "Trump")) +
  scale_y_continuous(limits=c(0, 100)) +
  scale_fill_manual(values =  c("Biden" = "blue",  "Trump" = "red")) +
  #geom_text(aes(label=round(..y..,2)), fun.y=mean, geom="text", vjust=-0.25, size=3.5, position=position_dodge(width=1))+
  theme_minimal() +
  theme(legend.position="none") +
  labs(
    title = "Term 'Big Business'",
     x = NULL,
     y = NULL
  )
```

```{r}
#plot final combined graphs above
library(ggplot2)
figure2 <- ggarrange(con_plot, bus_plot, common.legend = TRUE, legend="bottom") 

 annotate_figure(figure2,
               top = text_grob("Feeling Thermometer Averages - Agreements by Presidential Vote", color = "firebrick4", face = "bold", size = 14),
               bottom = text_grob("Data source: ANES", color = "grey5",
                                  hjust = 1, x = 1, face = "italic", size = 10),
               left = text_grob("Feeling Thermometer Rated 0-100", color = "grey5", rot = 90))

```

```{r}
#Saving previous plot
ggsave(filename = "Feeling Thermometer Agreements.png", plot = last_plot(), path = "Visualizations")
 
```

```{r}
#Selecting columns to keep for analysis and renaming them to make user friendly for long term data
RawData_LT_SC <- RawData_LongTerm %>% 
  select(
    year_lt = VCF0004,
    gender_lt = VCF0070b,
    income_group_lt = VCF0114,
    party_indentification = VCF0303,
    ft_lt_christian_fund = VCF0234,
    ft_lt_feminists = VCF0253,
    ft_lt_liberals = VCF0211,
    ft_lt_labor_unions = VCF0210,
    ft_lt_big_business = VCF0209,
    ft_lt_conservatives = VCF0212,
    ft_lt_congress = VCF0228,
    ft_lt_jews = VCF0205,
    ft_lt_police = VCF0214
    
  )
```

```{r}
#explore long term selected data
head(RawData_LT_SC, 10)
skim(RawData_LT_SC)
DataExplorer::create_report(RawData_LT_SC)
```

```{r}
#Change party identification variables for graph
RawData_LT_SC$party_indentification <- as.character(RawData_LT_SC$party_indentification)
RawData_LT_SC$party_indentification[RawData_LT_SC$party_indentification == "1"] <- "Democrats"
RawData_LT_SC$party_indentification[RawData_LT_SC$party_indentification == "2"] <- "Independents"
RawData_LT_SC$party_indentification[RawData_LT_SC$party_indentification == "3"] <- "Republicans"
RawData_LT_SC$party_indentification[RawData_LT_SC$party_indentification == "NA"] <- "Did not answer"
```

```{r}
#making combined data set
library(dplyr)


RawData_SC_Num_Sm <- RawData_SC_Num %>% 
  select(
    sex,
    total_income,
    party_of_registration,
    ft_christian_fund,
    ft_feminists,
    ft_liberals,
    ft_labor_unions,
    ft_big_business,
    ft_conservatives,
    ft_congress,
    ft_police,
    ft_jews)

RawData_SC_Num_Sm <- RawData_SC_Num_Sm %>% mutate(year_lt = 2020)

RawData_SC_Num_Sm <- RawData_SC_Num %>% 
  rename(
    gender_lt = sex,
    income_group_lt = total_income,
    party_indentification = party_of_registration,
    ft_lt_christian_fund = ft_christian_fund,
    ft_lt_feminists = ft_feminists,
    ft_lt_liberals = ft_liberals,
    ft_lt_labor_unions = ft_labor_unions,
    ft_lt_big_business = ft_big_business,
    ft_lt_conservatives = ft_conservatives,
    ft_lt_congress = ft_congress,
    ft_lt_police = ft_police,
    ft_lt_jews = ft_jews)

RawData_SC_Num_Sm_2 <- RawData_SC_Num_Sm[,c("year_lt", "gender_lt", "income_group_lt", "party_indentification","ft_lt_christian_fund",  "ft_lt_feminists", "ft_lt_liberals","ft_lt_labor_unions","ft_lt_big_business","ft_lt_conservatives", "ft_lt_congress", "ft_lt_police", "ft_lt_jews")]

long_term_2020 <- rbind(Data_LT_SC_C_NoNA, RawData_SC_Num_Sm_2)

long_term_2020$party_indentification[long_term_2020$party_indentification == "1"] <- "Democrats"
long_term_2020$party_indentification[long_term_2020$party_indentification == "4"] <- "Independents"
long_term_2020$party_indentification[long_term_2020$party_indentification == "2"] <- "Republicans"

lt_2020_filterd <- long_term_2020[!long_term_2020$party_indentification == "-1" | long_term_2020$party_indentification == "-6" | long_term_2020$party_indentification == "-7" | long_term_2020$party_indentification == "-8" | long_term_2020$party_indentification == "-9" | long_term_2020$party_indentification == "5",]

lt_2020_filterd2 <- lt_2020_filterd[!lt_2020_filterd$party_indentification == "-6",]
lt_2020_filterd3 <- lt_2020_filterd2[!lt_2020_filterd2$party_indentification == "-7",]
lt_2020_filterd4 <- lt_2020_filterd3[!lt_2020_filterd3$party_indentification == "5",]
lt_2020_filterd5 <- lt_2020_filterd4[!is.na(lt_2020_filterd4$party_indentification),]
lt_2020_filterd6 <- lt_2020_filterd5[!lt_2020_filterd5$party_indentification == "Independents",]
```    

```{r}
#long term feeling thermometer graph
ggplot(data = lt_2020_filterd6) +
  aes(x =(year_lt), y = ft_lt_liberals, fill=factor(party_indentification) ) +
  geom_bar(stat = "summary", width=1.75, position=position_dodge()) +
  theme_minimal() +
  coord_cartesian(xlim = c(1970,2020), ylim = c(0,75)) +
  labs(
    title = "Feeling Thermometer of Liberals by Year",
    subtitle = "Factored by Party",
    x = "Year",
    y = "Feeling Thermometer",
    caption = "Data via ANES",
  )
```

```{r}
#long term feeling thermometer graph
ggplot(data = lt_2020_filterd6) +
  aes(x =(year_lt), y = ft_lt_liberals, color=factor(party_indentification) ) +
  geom_line(stat = "summary", width=1.75, position=position_dodge()) +
  theme_minimal() +
  scale_colour_manual(values =  c("Democrats" = "blue",  "Republicans" = "red")) +
  coord_cartesian(xlim = c(1970,2020), ylim = c(0,75)) +
  labs(
    title = "Feeling Thermometer of Term 'Liberals' by Year",
    subtitle = "Factored by Party",
    x = "Year",
    y = "Feeling Thermometer Rated 0-100",
    caption = "Data via ANES",
  )
```

```{r}
#Saving previous plot
ggsave(filename = "Feeling Thermometer Liberals Line.png", plot = last_plot(), path = "Visualizations")
 
```

```{r}
#long term feeling thermometer graph
ggplot(data = lt_2020_filterd6) +
  aes(x =(year_lt), y = ft_lt_conservatives, color=factor(party_indentification) ) +
  geom_line(stat = "summary", width=1.75, position=position_dodge()) +
  theme_minimal() +
  scale_colour_manual(values =  c("Democrats" = "blue",  "Republicans" = "red")) +
  coord_cartesian(xlim = c(1970,2020), ylim = c(0,75)) +
  labs(
    title = "Feeling Thermometer of Term 'Conservatives' by Year",
    subtitle = "Factored by Party",
    x = "Year",
    y = "Feeling Thermometer Rated 0-100",
    caption = "Data via ANES",
  )
```

```{r}
#Saving previous plot
ggsave(filename = "Feeling Thermometer Conservatives Line.png", plot = last_plot(), path = "Visualizations")
 
```

```{r}
#Change party variables for graph
DataCharacters$party_of_registration <- as.character(DataCharacters$party_of_registration)
DataCharacters$party_of_registration[DataCharacters$party_of_registration == "-9"] <- "Refused"
DataCharacters$party_of_registration[DataCharacters$party_of_registration == "-8"] <- "Don't know"
DataCharacters$party_of_registration[DataCharacters$party_of_registration == "-7"] <- "Incomplete"
DataCharacters$party_of_registration[DataCharacters$party_of_registration == "-6"] <- "No post"
DataCharacters$party_of_registration[DataCharacters$party_of_registration == "-1"] <- "Inapplicable"
DataCharacters$party_of_registration[DataCharacters$party_of_registration == "1"] <- "Democratic"
DataCharacters$party_of_registration[DataCharacters$party_of_registration == "2"] <- "Republican"
DataCharacters$party_of_registration[DataCharacters$party_of_registration == "4"] <- "Independent"
DataCharacters$party_of_registration[DataCharacters$party_of_registration == "5"] <- "Other (Third party)"
```

```{r}
#Box plot
ggplot(data = DataCharacters) +
  aes(x = who_for_president, y = ft_blm, color = factor(party_of_registration)) +
  geom_point(size = 0.5, alpha = 0.25) +
  stat_boxplot(fill = NA) +
  scale_x_discrete(limits = c(1, 2)) +
  coord_cartesian(xlim = c(1,2), ylim = c(-10,105)) +
  labs(
    title = "Trump vs Biden Voters Feelings on BLM",
    subtitle = "Factored via Party",
    x = "Biden vs. Trump",
    y = "Feeling Thermometer",
    caption = "Data via ANES",
  )
```

```{r}
#Preparing data for animated visualization
RawData_LT_SC_Char <- RawData_LT_SC
RawData_LT_SC_Char$party_indentification <- as.character(RawData_LT_SC_Char$party_indentification)
RawData_LT_SC_Char$ft_lt_liberals <- as.factor(RawData_LT_SC_Char$ft_lt_liberals)
RawData_LT_SC_Char$ft_lt_conservatives <- as.factor(RawData_LT_SC_Char$ft_lt_conservatives)
RawData_LT_SC_Char$income_group_lt <- as.factor(RawData_LT_SC_Char$income_group_lt)
RawData_LT_SC_Char$year_lt <- as.integer(RawData_LT_SC_Char$year_lt)
Data_LT_SC_C_NoNA <- RawData_LT_SC_Char
Data_LT_SC_C_NoNA <- Data_LT_SC_C_NoNA[complete.cases(RawData_LT_SC_Char$ft_lt_liberals),]
Data_LT_SC_C_NoNA$ft_lt_liberals <- as.numeric(Data_LT_SC_C_NoNA$ft_lt_liberals)
Data_LT_SC_C_NoNA$ft_lt_conservatives <- as.numeric(Data_LT_SC_C_NoNA$ft_lt_conservatives)
Data_LT_SC_C_NoNA$income_group_lt <- as.numeric(Data_LT_SC_C_NoNA$income_group_lt)
Data_LT_SC_C_NoNA$ft_lt_labor_unions <- as.numeric(Data_LT_SC_C_NoNA$ft_lt_labor_unions)
Data_LT_SC_C_NoNA$ft_lt_big_business <- as.numeric(Data_LT_SC_C_NoNA$ft_lt_big_business)
Data_LT_SC_C_NoNA$party_indentification[Data_LT_SC_C_NoNA$party_indentification == "1"] <- "Democrats"
Data_LT_SC_C_NoNA$party_indentification[Data_LT_SC_C_NoNA$party_indentification == "2"] <- "Independents"
Data_LT_SC_C_NoNA$party_indentification[Data_LT_SC_C_NoNA$party_indentification == "3"] <- "Republicans"
Data_LT_SC_C_NoNA$party_indentification[Data_LT_SC_C_NoNA$party_indentification == "NA"] <- "Did not answer"
```

```{r}
#animation graph original
library(ggplot2)
library(gapminder)
library(gganimate)

animate(ggplot((data = Data_LT_SC_C_NoNA)) +
  aes(x = ft_lt_liberals, y = ft_lt_conservatives, size = income_group_lt, color = (party_indentification)) +
  geom_point(alpha = 0.7, show.legend = FALSE) +
  coord_cartesian(xlim = c(-15,115), ylim = c(-15,115)) +
  #scale_colour_manual(values = (party_indentification)) +
  facet_wrap(~party_indentification) +
  # Here comes the gganimate specific bits
  labs(title = 'Feeling Thermometer - Conservative vs Liberal by Year: {closest_state}', subtitle = "Split via Party - Size via Income Group", x = 'Feeling Thermometer - Liberals', y = 'Feeling Thermometer - Conservatives',caption = "Data via ANES") +
  transition_states(year_lt, transition_length = 1, state_length = 1000,
                    wrap = TRUE) +
     enter_fade() +
  exit_fade() +
  ease_aes('linear'),renderer = gifski_renderer())
```

```{r}
#updated and final animated graph
#WARNING TAKES SIGNIFICANT TIME AND COMPUTING POWER TO RENDER
library(ggplot2)
library(gapminder)
library(gganimate)
library(tweenr)

animate(ggplot((data = lt_2020_filterd6)) +
  aes(size = 1.5) +
  geom_jitter(alpha = 0.7, show.legend = TRUE, aes(x = ft_lt_liberals, y = ft_lt_conservatives, color =party_indentification)) +
  coord_cartesian(xlim = c(0,100), ylim = c(0,100)) +
  scale_colour_manual(values =  c("Democrats" = "blue",  "Republicans" = "red")) +
  facet_wrap(~party_indentification) +
  # Here comes the gganimate specific bits
  labs(title = 'Feeling Thermometer - Conservative vs Liberal by Year', subtitle =  "{closest_state}", x = 'Feeling Thermometer - Liberals', y = 'Feeling Thermometer - Conservatives',caption = "Data via ANES") +
  theme(plot.subtitle = element_text(color="red", size=14, face="bold.italic"), legend.position="bottom", legend.box = "horizontal") +
  guides(size = FALSE) +
  transition_states(year_lt, transition_length = 1, state_length = 3,
                    wrap = FALSE) +
  enter_fade() +
  exit_fade() +
  ease_aes('linear'),renderer = gifski_renderer(), duration = 30, end_pause = 45, fps = 30)
```

```{r}
#Import Data for Media Overview
library(haven)
RawData_SC_2 <- read_dta("/Users/Keith/Downloads/anes_timeseries_2020_stata_20210324/anes_timeseries_2020_stata_20210324.dta")
#selected columns
library(dplyr)
RawData_SC_Media <- RawData_SC_2 %>% 
  select(
    sex = V201600,
    party_of_registration = V202064,
    who_for_president = V202073,
    tv_programs = V201629a,
    newspapers = V201629b,
    internet = V201629c,
    radio = V201629d,
    stephen_colbert = V201630a,
    hannity = V201630b,
    tucker_carlson = V201630c,
    rachel_maddow = V201630d,
    the_five = V201630f,
    laura_ingram = V201630g,
    anderson_cooper = V201630j,
    abc = V201630n,
    nbc = V201630p,
    fox_friends = V201631k,
    morning_joe = V201631m,
    pbs = V201631q,
    nyt = V201636a,
    fox_com = V201634f
  )
#Labling for biden and trump
RawData_SC_Media$who_for_president <- as.character(RawData_SC_Media$who_for_president)
RawData_SC_Media$who_for_president[RawData_SC_Media$who_for_president == "1"] <- "Biden"
RawData_SC_Media$who_for_president[RawData_SC_Media$who_for_president == "2"] <- "Trump"
```

```{r}
#Fox news plot
fox_plot <- 
  ggplot(data = RawData_SC_Media) +
  aes(x =who_for_president, y =   fox_com, fill=who_for_president) +
  geom_bar(stat = "summary", width=1, color="gray1", position = 'dodge') +
  scale_fill_manual(values =  c("Biden" = "blue",  "Trump" = "red")) +
  geom_text(stat = "summary", fun = "mean",
            position = position_dodge(width = 1),
            aes(y = stage(fox_com, after_stat = y / 2),group = round(after_stat(y)),
                label = round(after_stat(y),digits =2),vjust=0)) +
  scale_x_discrete(limits=c("Biden", "Trump")) +
  scale_y_continuous(limits=c(0, 1)) +
  scale_fill_manual(values =  c("Biden" = "blue",  "Trump" = "red")) +
  #geom_text(aes(label=round(..y..,2)), fun.y=mean, geom="text", vjust=-0.25, size=3.5, position=position_dodge(width=1))+
  theme_minimal() +
  theme(legend.position="none") +
  labs(
    title = "FoxNews.com ",
     x = NULL,
     y = NULL
  )
```

```{r}
#NYT plot
nyt_plot <- 
  ggplot(data = RawData_SC_Media) +
  aes(x =who_for_president, y =   nyt, fill=who_for_president) +
  geom_bar(stat = "summary", width=1, color="gray1", position = 'dodge') +
  scale_fill_manual(values =  c("Biden" = "blue",  "Trump" = "red")) +
  geom_text(stat = "summary", fun = "mean",
            position = position_dodge(width = 1),
            aes(y = stage(nyt, after_stat = y / 2),group = round(after_stat(y)),
                label = round(after_stat(y),digits =2),vjust=0)) +
  scale_x_discrete(limits=c("Biden", "Trump")) +
  scale_y_continuous(limits=c(0, 1)) +
  scale_fill_manual(values =  c("Biden" = "blue",  "Trump" = "red")) +
  #geom_text(aes(label=round(..y..,2)), fun.y=mean, geom="text", vjust=-0.25, size=3.5, position=position_dodge(width=1))+
  theme_minimal() +
  theme(legend.position="none") +
  labs(
    title = "NewYorkTimes.com ",
     x = NULL,
     y = NULL
  )
```

```{r}
#Final plot for media visualization combinations
library(ggplot2)
figure3 <- ggarrange(fox_plot, nyt_plot, common.legend = TRUE, legend="bottom") 

 annotate_figure(figure3,
               top = text_grob("Fox News vs New York Times Percentage Use By Presidential Vote", color = "firebrick4", face = "bold", size = 14),
               bottom = text_grob("Data source: ANES", color = "grey5",
                                  hjust = 1, x = 1, face = "italic", size = 10),
               left = text_grob("Percentage Use", color = "grey5", rot = 90))

```


```{r}
#Saving previous plot
ggsave(filename = "FoxNewsvsNYT.png", plot = last_plot(), path = "Visualizations")
 
```


